In [ ]:
# # numpy Basics
# import numpy as np 

# lstone = np.array([[1,2,3],
#                    [5,6,7],
#                    [99,29,10]])
# lstone.shape


(3, 3)

##### scalar number 
##### vector (number,)
##### matrix (number , number) row X col
##### All dims called tensors

In [ ]:
# lsttwo = np.arange(0,10,1)
# lsttwo.reshape(2,5)
# lsttwo.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# lst3 = np.zeros((3,3))
# lst3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# lst4 = np.ones((3,3))
# lst4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# lst5 = np.full((3,3),6)
# lst5

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

#### From python list to ndarray

In [25]:
# python_lst = [1,2,3,4,5]
# ndarray = np.array(python_lst)
# ndarray.shape #(5,)

In [26]:
# # slicing an array 
# import numpy as np 
# lstone = np.array([[1,2,3,4,5],
#                    [6,7,8,9,10]])
# # lstone.shape
# lstone[1,::2]

##### 0 -> vertical col 
##### 1 -> horizontal rows

In [ ]:
# import numpy as np 


# # lstone = np.array([[ [1,2,3],
# #                      [4,5,6],
# #                      [7,8,9] ]])
# # np.sqrt(lstone)
# # np.max(lstone)
# # np.min(lstone)
# # np.absolute(lstone)
# # np.log(lstone)
# # np.cos(lstone)
# # np.sin(lstone)



# # lstone = np.array([1,2,3])
# # lst_to_append = np.array([4,5,6])
# # np.append(lstone , lst_to_append)
# # np.amax(lstone)
# lstone = np.array([[10,2,3],
#                    [4,5,6]])
# # lstone.max(axis=0)
# # lstone.max(axis=1)
# # lstone.sum(axis=1)



##### View vs copy

if u change the OG view will also change
copy is otherwise
you cant change copy if u had changed the original `it is already different array`

In [ ]:
# import numpy as np 

# threedimArray = np.array(
#     [
#      [[1,2,3],
#       [4,5,6]]
#      ,
#      [[1,2,3],
#       [4,5,6]]
        
#         ]
# )

# # (1,2,3)

# threedimArray.shape

# flat = threedimArray.reshape(-1)
# flat


# # lstview = lstone.view() 
# # lstone[0] = 30
# # lstview

# # lstcopy = lstone.copy("C")
# # lstone[0] = 30
# # lstcopy

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [ ]:
# # iteriate in np array using np.nditer()

# # creating 3d tensor 
# import numpy as np 

# arr = np.array(
#     [
#         [
#             [1,2,3],
#             [4,5,6]
#         ],
#         [
#             [1,2,3],
#             [4,5,6]
#         ]
#     ]
# )
# arr.shape
# # for x in np.nditer(arr):
# #     print(x)
    
# # or

# # for x in arr : 
# #     for y in x : 
# #         for z in y : 
# #             print(z)



1
2
3
4
5
6
1
2
3
4
5
6


In [ ]:
# # sort using : np.sort()
# import numpy as np 


# arr = np.array(
#     [
#         [
#             [10 , 200 ,20],
#             [4,5,6]
#         ]
#     ]
# )

# np.sort(arr)

array([[[ 10,  20, 200],
        [  4,   5,   6]]])

In [ ]:
# # filter array 
# import numpy as np 

# arr = np.array([
#     [1,2,3],
#     [4,5,6]
# ])

# z = arr.reshape(-1)
# v = z.tolist()

# felt = filter(lambda n : n % 2 == 0 , v)
# list(felt)

[2, 4, 6]

In [ ]:
# import numpy as np 


# arr = np.array(
#     [
#         [1,2,3],
#         [4,5,6]
#     ]
# )

# arr2 = np.array(
#     [
#         [1,2,3],
#         [4,5,6]
#     ]
# )







# # arr.flatten()
# # arr.reshape(-1)
# # arr.transpose()
# # arr.T
# # z = np.concatenate([arr , arr2])
# # x = np.stack([arr,arr2]) # they are both alike but stack add one dimension 
# # print(z.ndim , x.ndim)




2 3


In [ ]:
# import numpy as np 


# z = np.random.randint(0,10 ,(2,3)) # zero to 10 but (2,3) shape
# z


array([[8, 1, 6],
       [0, 2, 8]], dtype=int32)

In [ ]:
# import numpy as np 

# arr = np.array([1,2,3,4,5,6,7,8])
# np.split(arr,8) # split must have to be on division 

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8])]

In [ ]:
# import numpy as np 
# #فـ linspace يقولك: تعال نقسم المسافة من 0 لـ 1 لـ 5 أجزاء متساوية.
# z = np.linspace(-5 , 5 , 4) # gonna use it matplotlib  
# z

array([-5.        , -1.66666667,  1.66666667,  5.        ])